---
development:
  cloud_name: kl3-clarke
  api_key: '449567698494437'
  api_secret: 8tfrmCzYXH4nHTPfHoSfV67KCxs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: kl3-clarke
  api_key: '449567698494437'
  api_secret: 8tfrmCzYXH4nHTPfHoSfV67KCxs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: kl3-clarke
  api_key: '449567698494437'
  api_secret: 8tfrmCzYXH4nHTPfHoSfV67KCxs
  enhance_image_tag: true
  static_file_support: false
